# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-22 08:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入用户名', max_length=20, unique=True, verbose_name='妮称')),
                ('mobile', models.CharField(blank=True, help_text='请输入手机号码', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误')], verbose_name='手机号码')),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='密码')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('school', models.CharField(blank=True, help_text='请输入学校地址', max_length=100, null=True, verbose_name='学校')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=200, null=True, verbose_name='地址')),
                ('add_date', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
