# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-22 13:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误'), django.core.validators.MinLengthValidator(11)], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='妮称'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, null=True, verbose_name='性别'),
        ),
    ]
