# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180922_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
