# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_bthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='fromshome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='故乡'),
        ),
    ]
