# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180925_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaddress',
            options={'verbose_name': '收费地址', 'verbose_name_plural': '收费地址'},
        ),
        migrations.AlterModelOptions(
            name='cartcommodity',
            options={'verbose_name': '订单商品表', 'verbose_name_plural': '订单商品表'},
        ),
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='carttransport',
            options={'verbose_name': '运输方式', 'verbose_name_plural': '运输方式'},
        ),
        migrations.AlterModelOptions(
            name='goods_cla',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='goods_photo',
            options={'verbose_name': '商品相册', 'verbose_name_plural': '商品相册'},
        ),
        migrations.AlterModelOptions(
            name='goods_spu',
            options={'verbose_name': '商品SPU表', 'verbose_name_plural': '商品SPU表'},
        ),
        migrations.AlterModelOptions(
            name='goods_unit',
            options={'verbose_name': '商品单位表', 'verbose_name_plural': '商品单位表'},
        ),
        migrations.AlterModelOptions(
            name='indexactive',
            options={'verbose_name': '首页活动表', 'verbose_name_plural': '首页活动表'},
        ),
        migrations.AlterModelOptions(
            name='indexflashimg',
            options={'verbose_name': '首页轮播商品表', 'verbose_name_plural': '首页轮播商品表'},
        ),
        migrations.AlterModelOptions(
            name='indexzone',
            options={'verbose_name': '首页活动专区', 'verbose_name_plural': '首页活动专区'},
        ),
        migrations.AlterModelOptions(
            name='indexzoneactive',
            options={'verbose_name': '首页专区活动商品表', 'verbose_name_plural': '首页专区活动商品表'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': '支付方式', 'verbose_name_plural': '支付方式'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='headimg',
            field=models.ImageField(default='default/shop1.png', upload_to='shop/%Y%m/%d', verbose_name='用户头像'),
        ),
        migrations.AlterModelTable(
            name='goods_cla',
            table='Goods_cla',
        ),
        migrations.AlterModelTable(
            name='goods_sku',
            table='Goods_SKU',
        ),
    ]
