# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-25 11:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180925_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_spu',
            name='spu_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='goods_unit',
            name='unit_goods_unit',
            field=models.CharField(max_length=10, verbose_name='商品单位'),
        ),
    ]
